# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0002_auto_20170620_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=38)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=38)),
                ('category', models.CharField(max_length=255)),
                ('publish', models.DateTimeField(max_length=38)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
