# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0003_auto_20170620_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default=b'', max_length=38),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
