# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0004_auto_20170620_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(default=True),
        ),
    ]
