# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0005_books_in_print'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=38)),
                ('description', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
